version: '3.6' # specify docker-compose version

# Define the services/containers to be run
services:
  angular:
    hostname: localhost
    build: angular-application
    ports:
      - 8181:80
  express: 
    build: express-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database

  database: 
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding